fix: use 00:00:00 and 24:00:00 for LocalTime.MIN/MAX (#992)
'infinity'::time does not work, so 00:00:00 and 24:00:00 are used.

# select '24:00:01'::time;
ERROR:  date/time field value out of range: "24:00:01"
LINE 1: select '24:00:01'::time;

fixes #991

(cherry picked from commit f2d8ec5)